name: Publish

on:
  push:

jobs:
  validate:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.WRANGLER_TOKEN }}
